In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('titanic_data.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,no,third,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,yes,first,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,yes,third,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,yes,first,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,no,third,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
print(f"Total potential features: {df.shape[1]}")
print(f"Total sample data: {df.shape[0]}")

Total potential features: 12
Total sample data: 891

In [16]:
df.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
294,295,no,third,"Mineff, Mr. Ivan",male,24.0,0,0,349233,7.8958,NaN,S
300,301,yes,third,"Kelly, Miss. Anna Katherine ""Annie Kate""",female,NaN,0,0,9234,7.7500,NaN,Q
579,580,yes,third,"Jussila, Mr. Eiriik",male,32.0,0,0,STON/O 2. 3101286,7.9250,NaN,S
65,66,yes,third,"Moubarek, Master. Gerios",male,NaN,1,1,2661,15.2458,NaN,C
62,63,no,first,"Harris, Mr. Henry Birkhardt",male,45.0,1,0,36973,83.4750,C83,S
476,477,no,second,"Renouf, Mr. Peter Henry",male,34.0,1,0,31027,21.0000,NaN,S
888,889,no,third,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
399,400,yes,second,"Trout, Mrs. William H (Jessie L)",female,28.0,0,0,240929,12.6500,NaN,S
733,734,no,second,"Berriman, Mr. William John",male,23.0,0,0,28425,13.0000,NaN,S
709,710,yes,third,"Moubarek, Master. Halim Gonios (""William George"")",male,NaN,1,1,2661,15.2458,NaN,C

### 1.3 Input Screening

In [17]:
#missing value
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [19]:
# checking duplicate value
df.duplicated().sum()
df.drop_duplicates(inplace=True)