In [31]:
import numpy as np

w = np.array([2,2,])
x = np.array([2,2,])
dot = np.dot(w, x)
dot

np.int64(8)

Normal Distribution

In [32]:
random = np.random.seed(42)

In [33]:
random_normal = np.random.random(3)
random_normal

array([0.37454012, 0.95071431, 0.73199394])

In [34]:
random = np.random.rand(3)
random

array([0.59865848, 0.15601864, 0.15599452])

concatenation

In [35]:
import pandas as pd
data = pd.DataFrame({
    "x1": [1, 2, 3, 4, 5],
    "x2": [5, 4, 3, 2, 1],
    "y": [0, 1, 0, 1, 0]
})

AND = pd.DataFrame(data)

In [36]:
AND

   x1  x2  y
0   1   5  0
1   2   4  1
2   3   3  0
3   4   2  1
4   5   1  0

In [37]:
X = AND.drop("y", axis=1)
y = AND["y"]
y.to_frame()

   y
0  0
1  1
2  0
3  1
4  0

In [38]:
bias = np.c_[X, -np.ones((len(X), 1))]
bias

array([[ 1.,  5., -1.],
       [ 2.,  4., -1.],
       [ 3.,  3., -1.],
       [ 4.,  2., -1.],
       [ 5.,  1., -1.]])

In [39]:
len(X)

5

Main implementation

In [44]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [41]:
class Perceptron:
    def __init__(self,eta,epochs):
        self.waights = np.random.rand(3) * 1e-4
        print(f"Initial weights: {self.waights}")
        self.eta = eta
        self.epochs = epochs
    
    def activation_function(self,input,waights):
        z = np.dot(input, waights)
        return np.where(z >= 0.0, 1, 0)

    def fit(self,X,y):
        self.X = X
        self.y = y
        
        x_with_bias = np.c_[self.X, -np.ones((len(X), 1))]
        print(f"X with bias: {x_with_bias}")
        
        for epoch in range(self.epochs):
            print("Epoch:", epoch)
        
            y_hat = self.activation_function(x_with_bias, self.waights)
            print(f"Predicted values: {y_hat}")
        
            error = self.y - y_hat
            print(f"Error: {error}")
        
            #waights update
            self.waights += self.eta * np.dot(x_with_bias.T, error)
            print(f"Updated weights: {self.waights}")
        
        
            print("#############################")
            
    def predict(self,X):
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        
        return self.activation_function(X_with_bias, self.waights)

In [42]:
import pandas as pd
data = pd.DataFrame({
    "x1": [1, 2, 3, 4, 5],
    "x2": [5, 4, 3, 2, 1],
    "y": [0, 1, 0, 1, 0]
})

AND = pd.DataFrame(data)

x = AND.drop("y", axis=1)
y = AND["y"]
y.to_frame()

   y
0  0
1  1
2  0
3  1
4  0

#model Prediction

In [43]:
model = Perceptron(eta=0.5, epochs=10)
model.fit(x,y)

Initial weights: [5.80836122e-06 8.66176146e-05 6.01115012e-05]
X with bias: [[ 1.  5. -1.]
 [ 2.  4. -1.]
 [ 3.  3. -1.]
 [ 4.  2. -1.]
 [ 5.  1. -1.]]
Epoch: 0
Predicted values: [1 1 1 1 1]
Error: 0   -1
1    0
2   -1
3    0
4   -1
Name: y, dtype: int64
Updated weights: [-4.49999419 -4.49991338  1.50006011]
#############################
Epoch: 1
Predicted values: [0 0 0 0 0]
Error: 0    0
1    1
2    0
3    1
4    0
Name: y, dtype: int64
Updated weights: [-1.49999419 -1.49991338  0.50006011]
#############################
Epoch: 2
Predicted values: [0 0 0 0 0]
Error: 0    0
1    1
2    0
3    1
4    0
Name: y, dtype: int64
Updated weights: [ 1.50000581  1.50008662 -0.49993989]
#############################
Epoch: 3
Predicted values: [1 1 1 1 1]
Error: 0   -1
1    0
2   -1
3    0
4   -1
Name: y, dtype: int64
Updated weights: [-2.99999419 -2.99991338  1.00006011]
#############################
Epoch: 4
Predicted values: [0 0 0 0 0]
Error: 0    0
1    1
2    0
3    1
4    0
Name: y, dtype: int64
Updated weights: [5.80836122e-06 8.66176146e-05 6.01115012e-05]
#############################
Epoch: 5
Predicted values: [1 1 1 1 1]
Error: 0   -1
1    0
2   -1
3    0
4   -1
Name: y, dtype: int64
Updated weights: [-4.49999419 -4.49991338  1.50006011]
#############################
Epoch: 6
Predicted values: [0 0 0 0 0]
Error: 0    0
1    1
2    0
3    1
4    0
Name: y, dtype: int64
Updated weights: [-1.49999419 -1.49991338  0.50006011]
#############################
Epoch: 7
Predicted values: [0 0 0 0 0]
Error: 0    0
1    1
2    0
3    1
4    0
Name: y, dtype: int64
Updated weights: [ 1.50000581  1.50008662 -0.49993989]
#############################
Epoch: 8
Predicted values: [1 1 1 1 1]
Error: 0   -1
1    0
2   -1
3    0
4   -1
Name: y, dtype: int64
Updated weights: [-2.99999419 -2.99991338  1.00006011]
#############################
Epoch: 9
Predicted values: [0 0 0 0 0]
Error: 0    0
1    1
2    0
3    1
4    0
Name: y, dtype: int64
Updated weights: [5.80836122e-06 8.66176146e-05 6.01115012e-05]
#############################

# XOR

In [47]:
data ={
    "x1": [0, 0, 1, 1],
    "x2": [0, 1, 0, 1],
    "y": [0, 1, 1, 0]
}
XOR = pd.DataFrame(data)

X = XOR.drop("y", axis=1)

y = XOR["y"]
y.to_frame()

model = Perceptron(eta=0.01, epochs=1000)
model.fit(X,y)

Initial weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
X with bias: [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch: 0
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 1
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 2
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 3
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 4
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 5
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 6
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 7
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 8
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 9
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 10
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 11
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 12
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 13
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 14
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 15
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 16
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 17
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 18
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 19
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 20
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 21
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 22
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 23
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 24
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 25
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 26
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 27
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 28
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 29
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 30
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 31
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 32
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 33
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 34
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 35
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 36
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 37
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 38
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 39
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 40
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 41
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 42
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 43
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 44
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 45
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 46
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 47
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 48
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 49
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 50
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 51
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 52
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 53
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 54
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 55
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 56
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 57
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 58
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 59
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 60
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 61
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 62
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 63
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 64
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 65
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 66
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 67
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 68
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 69
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 70
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 71
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 72
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 73
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 74
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 75
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 76
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 77
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 78
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 79
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 80
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 81
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 82
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 83
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 84
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 85
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 86
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 87
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 88
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 89
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 90
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 91
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 92
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 93
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 94
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 95
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 96
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 97
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 98
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 99
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 100
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 101
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 102
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 103
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 104
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 105
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: [1.83404510e-05 3.04242243e-05 5.24756432e-05]
#############################
Epoch: 106
Predicted values: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: [ 0.01001834  0.01003042 -0.01994752]
#############################
Epoch: 107
Predicted values: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64