# Structure of a functions -Paramiters

In [3]:
def welcome_message():
    print("Hello Bro")

In [4]:
welcome_message()

Hello Bro

In [9]:
def welcome_message(user = "None"):
    print(f"Hello {user}")

In [10]:
welcome_message()

Hello None

In [ ]:
def adder(a,b) :
    """
    this function add two number  
    """ #we use """ """ to define function it calld Doc we can call help() function 
    
    sum = a+b
    # print(sum) this can't usable for future arithmetic use so we will use return
    return sum

In [14]:
m = adder(3,5) * 4
print(m)

32

In [1]:
def adder(*args) :
    for i in args:
        print(i)
        
        
adder(10,11,11,2)

10
11
11
2

## Keyword Arguments

In [2]:
def adder(a,b,c):
    print(f"{a},{b},{c}")
    
adder(a=3,c=5,b=1)

3,1,5

In [5]:
def adder(**kwargs):
    for key,value in kwargs.items():
        print(f"{key}: {value}")
    
adder(a=12, b=5,c=40, n_estimatoe=50)

a: 12
b: 5
c: 40
n_estimatoe: 50

## Return Type

In [7]:
def welcome_message() :
    print("Hello User")
    
print(type(welcome_message()))

Hello User
<class 'NoneType'>

In [8]:
def adder(a,b):
    sum = a+b
    return sum

print(type(adder(10,20)))

<class 'int'>

In [10]:
def welcome_message(user = "none") :
    return f"Hello {user}"
    
print(type(welcome_message()))

<class 'str'>

In [12]:
def adder(a,b):
    return a,b

print(type(adder(10,20)))

#unzip
x,y = adder(10.5,10)
print(x,y)

<class 'tuple'>
10.5 10

## Iterator

In [24]:
s ={10,20,30,50}

s_iter = iter(s)


print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))

for value in s:
    print(value)

10
20
50
30
10
20
50
30

In [ ]:
dic = {
    "Name" : "Bipro",
    "Age" : 24,
    "Gender" : "Male",
     
}
dic_iter = iter(dic.items()) #.keys() or .values() for only keys or valus
print(next(dic_iter))
print(next(dic_iter))
print(next(dic_iter))

('Name', 'Bipro')
('Age', 24)
('Gender', 'Male')

## Generator

In [42]:
list = [x for x in range(500)]

def data_loader(chunk_size,list):
    for i in range(0,len(list),chunk_size):
        yield list[i:i+chunk_size]
        
x = data_loader(5,list)

# print(type(x))
print(next(x))
print(next(x))
print(next(x))
print(next(x))
print(next(x))
print(next(x))

[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]
[10, 11, 12, 13, 14]
[15, 16, 17, 18, 19]
[20, 21, 22, 23, 24]
[25, 26, 27, 28, 29]

## Lambda ,Filter ,Apply Function

In [ ]:
import pandas as pd

df = pd.DataFrame({'Temperature(F)' : [21,11,89.6,98]})
df

df['Temperature(C)'] = df['Temperature(F)'].apply(lambda x: (x-32) * 5/9) #apply function can use as map

df

   Temperature(F)  Temperature(C)
0            21.0       -6.111111
1            11.0      -11.666667
2            89.6       32.000000
3            98.0       36.666667

In [ ]:
import pandas as pd
df = pd.DataFrame({'A' : [1,2,3,4,5],'B' : [6,7,8,9,10]})

df['A'] = df['A'].map(lambda x : x ** 0.5)

df

          A   B
0  1.000000   6
1  1.414214   7
2  1.732051   8
3  2.000000   9
4  2.236068  10

In [52]:
import pandas as pd 
df = pd.DataFrame({'Total_spent' : [120,690,300,600]})

#creating a high value feature
df['Is_High_value'] = df['Total_spent'].apply(lambda x : 1 if x>500 else 0)
 
df

   Total_spent  Is_High_value
0          120              0
1          690              1
2          300              0
3          600              1